In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)
     

2.11.0


In [3]:
## importing libraries
import numpy as np 
import matplotlib.pyplot as plt
import pandas as pd
     

In [4]:
dataset=pd.read_csv('Churn_Modelling.csv')
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [5]:
#seperating the dataset 
X=dataset.iloc[:,3:13]
y=dataset.iloc[:,13]

In [6]:
X.head(3)

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57

In [7]:
y.head(3)

0    1
1    0
2    1
Name: Exited, dtype: int64

In [8]:
pd.get_dummies(X['Geography'],drop_first=True)

Germany  Spain
0           0      0
1           0      1
2           0      0
3           0      0
4           0      1
...       ...    ...
9995        0      0
9996        0      0
9997        0      0
9998        1      0
9999        0      0

[10000 rows x 2 columns]

In [9]:
geography=pd.get_dummies(X['Geography'],drop_first=True)

In [10]:
gender=pd.get_dummies(X['Gender'],drop_first=True)

In [11]:
gender.head(2)

Male
0     0
1     0

In [12]:
X=X.drop(['Geography','Gender'],axis=1)

In [13]:
X.head(3)

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619   42       2       0.00              1          1   
1          608   41       1   83807.86              1          0   
2          502   42       8  159660.80              3          1   

   IsActiveMember  EstimatedSalary  
0               1        101348.88  
1               1        112542.58  
2               0        113931.57

In [14]:
#concatination
X=pd.concat([X,geography,gender],axis=1)

In [15]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [16]:
#feature scaling

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [17]:
X_train

array([[ 0.16958176, -0.46460796,  0.00666099, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       [-2.30455945,  0.30102557, -1.37744033, ...,  1.75486502,
        -0.57369368,  0.91601335],
       [-1.19119591, -0.94312892, -1.031415  , ..., -0.5698444 ,
        -0.57369368, -1.09168714],
       ...,
       [ 0.9015152 , -0.36890377,  0.00666099, ..., -0.5698444 ,
        -0.57369368,  0.91601335],
       [-0.62420521, -0.08179119,  1.39076231, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       [-0.28401079,  0.87525072, -1.37744033, ...,  1.75486502,
        -0.57369368, -1.09168714]])

In [18]:
X_test

array([[-0.55204276, -0.36890377,  1.04473698, ...,  1.75486502,
        -0.57369368, -1.09168714],
       [-1.31490297,  0.10961719, -1.031415  , ..., -0.5698444 ,
        -0.57369368, -1.09168714],
       [ 0.57162971,  0.30102557,  1.04473698, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       ...,
       [-0.74791227, -0.27319958, -1.37744033, ..., -0.5698444 ,
         1.74309049,  0.91601335],
       [-0.00566991, -0.46460796, -0.33936434, ...,  1.75486502,
        -0.57369368,  0.91601335],
       [-0.79945688, -0.84742473,  1.04473698, ...,  1.75486502,
        -0.57369368,  0.91601335]])

In [19]:
X_train.shape

(8000, 11)

In [20]:
### Now lets creat ANN
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import LeakyReLU, PReLU, ELU, ReLU
from tensorflow.keras.layers import Dropout

In [21]:
# lets initialize the ANN
Classifier=Sequential()

In [22]:
# adding the input layer
Classifier.add(Dense(units=11,activation='relu'))

In [23]:
# adding the first hidden layer
Classifier.add(Dense(units=7,activation='relu'))

In [24]:
# adding the second hidden layer
Classifier.add(Dense(units=6,activation='relu'))

In [25]:
## adding the output layer
Classifier.add(Dense(units=1,activation='sigmoid'))

In [26]:
Classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [27]:
model_history=Classifier.fit(X_train,y_train,validation_split=0.33,batch_size=10,epochs=50)

Epoch 1/50
536/536 [==============================] - 5s 4ms/step - loss: 0.5135 - accuracy: 0.7934 - val_loss: 0.4674 - val_accuracy: 0.7955
Epoch 2/50
536/536 [==============================] - 2s 3ms/step - loss: 0.4474 - accuracy: 0.7972 - val_loss: 0.4402 - val_accuracy: 0.8008
Epoch 3/50
536/536 [==============================] - 2s 3ms/step - loss: 0.4191 - accuracy: 0.8132 - val_loss: 0.4175 - val_accuracy: 0.8190
Epoch 4/50
536/536 [==============================] - 2s 3ms/step - loss: 0.3880 - accuracy: 0.8377 - val_loss: 0.3975 - val_accuracy: 0.8300
Epoch 5/50
536/536 [==============================] - 2s 3ms/step - loss: 0.3659 - accuracy: 0.8470 - val_loss: 0.3829 - val_accuracy: 0.8342
Epoch 6/50
536/536 [==============================] - 2s 3ms/step - loss: 0.3550 - accuracy: 0.8545 - val_loss: 0.3763 - val_accuracy: 0.8432
Epoch 7/50
536/536 [==============================] - 2s 3ms/step - loss: 0.3489 - accuracy: 0.8546 - val_loss: 0.3758 - val_accuracy: 0.8448
Epoch 

In [28]:
model_history.history.keys()

dict_keys(['loss', 'accuracy', 'val_loss', 'val_accuracy'])

In [29]:
## now making the predictions and evaluating the model
y_pred = Classifier.predict(X_test)
y_pred = (y_pred >= 0.5)

63/63 [==============================] - 0s 2ms/step


In [30]:
# making the confusion matrix
from sklearn.metrics import confusion_matrix

In [31]:
cm=confusion_matrix(y_test,y_pred)
cm

array([[1504,   91],
       [ 191,  214]], dtype=int64)

In [32]:

## Calculating the accuracy
from sklearn.metrics import accuracy_score
score=accuracy_score(y_pred,y_test)

In [33]:
score

0.859

In [34]:
## to get the weights 
Classifier.get_weights()

[array([[ 4.85841825e-04, -4.98354845e-02, -4.66001868e-01,
          1.10420309e-01,  1.74411923e-01,  9.16618854e-02,
         -1.45270631e-01, -1.64011136e-01, -8.17612410e-02,
          1.45112485e-01,  4.34693433e-02],
        [ 6.28183305e-01,  2.04512164e-01, -6.80104733e-01,
         -1.00024617e+00, -2.66589671e-01, -3.95024747e-01,
         -7.19801366e-01, -1.02726392e-01, -5.40859461e-01,
         -3.92956525e-01, -3.32095593e-01],
        [ 1.52980343e-01,  1.43219084e-01, -1.43335775e-01,
          1.66353017e-01,  2.90806651e-01,  1.78120639e-02,
          2.27387741e-01, -4.17214930e-01, -1.88689500e-01,
         -1.12272434e-01,  6.25858903e-01],
        [-3.75449419e-01, -4.43619750e-02, -3.25570524e-01,
          4.16756235e-02,  1.83438078e-01, -2.42012963e-01,
         -1.12022549e-01, -3.69862080e-01, -8.19686651e-02,
         -1.05667186e+00, -3.02364737e-01],
        [-1.93535425e-02,  1.07423770e+00, -2.71389753e-01,
         -4.92273569e-01, -3.77104372e-01,  